apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-sharded-controller-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-sharded-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-sharded-controller-role
subjects:
- kind: ServiceAccount
  name: my-sharded-controller-controller-manager
  namespace: my-sharded-controller-system
