apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharding:controllerring:my-controller-ring
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sharding:controllerring:my-controller-ring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sharding:controllerring:my-controller-ring
subjects:
- kind: ServiceAccount
  name: sharder
  namespace: sharding-system
