apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    shard.alpha.sharding.timebertt.dev/go-controller-ring: go-sharded-controller-<pod-name>
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause
