---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.mydomain.com
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.mydomain.com
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps.mydomain.com
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
