apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-1
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-2
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-3
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-4
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-5
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-6
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-7
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-8
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-9
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
- apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-10
    labels:
      app: test
  spec:
    containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
